# Site settings
theme: jekyll-theme-cayman
title: Audi 100
email: ch.trautwein@bmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: trautw
github_username:  trautw

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
